version: '3'
services:
  database:
    image: "postgres"
    ports:
        - "55000:5432"
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data:
